# Generated by Django 3.2 on 2021-04-14 08:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('fetching_status', models.IntegerField(choices=[(1, 'Started'), (2, 'Fetched'), (3, 'Failed')], default=1, editable=False)),
            ],
        ),
    ]
